### DISCUSSION TITLE
Best practices for an app that edits a yaml file?

### DISCUSSION THREAD

**Discussion by justyns** [windmill-labs/windmill#1762] [Questions]
I'm not entirely sure if Windmill will be good at this or not, but I'm hoping it will work.  Any advice is appreciated.

I currently have a yaml file with a list of apps in it.  I have a separate script which parses this and for each app, it renders a hashicorp nomad job file or kubernetes manifest.   Currently I edit this by hand, but I want a nice UI for it.

As an example, here's a basic app in the list:

``` yaml
  - name: whoami
    image: jwilder/whoami
    http_port: 8000
    count: 2
```

And here's a more complicated one with more options:

``` yaml
  - name: windmill-worker
    count: 3
    image: ghcr.io/windmill-labs/windmill:1.114.2
    has_inbound: False
    # user: 1100:1100
    env:
      RUST_LOG: info
      BASE_URL: https://windmill.lan.x
      BASE_INTERNAL_URL: https://windmill.lan.x
      NUM_WORKERS: 1
      DISABLE_SERVER: "true"
      METRICS_ADDR: "false"
      KEEP_JOB_DIR: "false"
      TIMEOUT: "3600"
    vault_policies:
      - nomad-windmill
    vault_env_template: |
      {{with secret "kv/data/nomad/windmill"}}
      {{ range $k, $v := .Data.data }}
      {{ $k }}={{ $v | toJSON }}
      {{end}}
      {{end}}
    constraints:
      "${meta.mount_home_nfs}": "True"
```

In windmill, I have an app that can clone the git repo where this yaml file is stored and runs a python script which converts the yaml into json and displays it in an AgTable.

<img width="846" alt="image" src="https://github.com/windmill-labs/windmill/assets/215985/71faeba0-058c-48e2-a5d2-9c27fd6002e8">

I think this is where I'm a little lost.    Some of the keys are too complex to edit in a table, so I thought I could just make a form to the side of the table where it'd be easier.  This works for some of the keys like name/image/count, but I'm not sure how to handle the more complex ones like `env` which is a nested object.

Are there any examples of something vaguely similar, or maybe just some advice on handling complex/nested objects?

I don't really want to convert the yaml file to a database, but I'm wondering if it would make it easier to manipulate with windmill?
