### ISSUE TITLE
bug: Getting error on uploading CSV file > 1 mb 

### ISSUE THREAD

**Issue by deadlocks** [windmill-labs/windmill#1772]
### Describe the bug

I am getting an error if CSV file greater than 1mb is uploaded

### To reproduce

1. Go to scripts and add Python script 
2. Trying to upload a csv file > 1mb in default example
3. Click Run

### Expected behavior

The file should be read by script, if there's another way to upload and read files from the local system, I can use that too. But I couldn't find it in the documentation. All method involve cloud solution

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/2733405/adafb5cc-0292-49ee-90c0-4ba64b1e2d70)

**Comment by AxelRothe** [comment]
Same here. Trying to send a 1.2MB large base64 string in the payload will result in "length limit exceeded". Can confirm that this is not on our end. Double checked both nginx and express on our end and our service works fine via REST. But whenever I try to send >1MB large files to our servers I get the same error.

**Comment by rubenfiszel** [comment]
The server uses axum which has a default abuse protection by limiting the size of the input request to 2MB. On self-hosted setup, you can increase this by configuring: REQUEST_SIZE_LIMIT. This env variable is described in the README.md

On the cloud, we can raise this limit for dedicated enterprise accounts but we currently cannot do it for the multi-tenant setup (we will improve this in the future).

**Comment by AxelRothe** [comment]
> The server uses axum which has a default abuse protection by limiting the size of the input request to 2MB. On self-hosted setup, you can increase this by configuring: REQUEST_SIZE_LIMIT. This env variable is described in the README.md

Yes, I added the ENV. The error occurs at +1MB and not at 2MB, so I think there is something not setting the value to what I set it in the .env file. I tried values from 5MB to 100MB, it will still only accept 1MB files.

**Comment by rubenfiszel** [comment]
I can confirm to you that by modifying the windmill_server section of the docker compose by adding REQUEST_SIZE_LIMIT
e.g:
```
  windmill_server:
    # Use ghcr.io/windmill-labs/windmill-ee:main for the ee
    image: ghcr.io/windmill-labs/windmill:main
    pull_policy: always
    deploy:
      replicas: 1
    restart: unless-stopped
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db/windmill?sslmode=disable
      - BASE_URL=${WM_BASE_URL}
      - RUST_LOG=info
      ## You can set the number of workers to > 0 and not need any separate worker service but not recommended
      - NUM_WORKERS=0
      - DISABLE_SERVER=false
      - METRICS_ADDR=false
      - REQUEST_SIZE_LIMIT=10000000000
 ```

you can pass inputs who are bigger than 1MB (I just tested with 26.5MB)
