### ISSUE TITLE
bug:"Failed to send email to <email>: TLS error: received corrupt message of type InvalidContentType"

### ISSUE THREAD

**Issue by Anton-Shutik** [windmill-labs/windmill#2245]
### Describe the bug

Invite email is not sent when SMTP configured

### To reproduce

1. Go to superadmin settings
2. Add new user

### Expected behavior

Invite email should be sent

### Application version

Windmill CE v1.168.2-12-g7c68f589

**Comment by rubenfiszel** [comment]
I will need more information because it seems to be specific to your SMTP settings/provider

**Comment by Anton-Shutik** [comment]
Here is what I have in helm chart:

```
windmill:
  tag: "latest"
    .......
  smtp:
    # enable smtp for sending emails
    enabled: true
    # smtp server to use for sending emails
    host: smtp.gmail.com
    # smtp port to use for sending emails
    port: 587
    # smtp username to use for sending emails
    username: "svc-windmill@<domain.com>"
    # smtp from address to use for sending emails
    from: "svc-windmill@<domain.com>"
    # smtp tls
    tls_implicit: true
    # password
    password: "password"
```
