### ISSUE TITLE
bug: provided docker-compose.yml may lead to out of memory errors for native workers

### ISSUE THREAD

**Issue by abrasher** [windmill-labs/windmill#2480]
### Describe the bug

I was trying to run a REST script but the test wasn't loading at all.

At first I tried restarting the stack. Then, I found out the native worker containers were stuck rebooting due to out of memory errors. I tried to stop and remove the containers and then add them again but didn't solve it.

I ran the containers at 256m and they cleared out a bunch of actions (jobs I think? they logged a lot of output at once)

After that I could run the containers at 128mb again. 

I am unsure what "built up" (or how it first started) leading to the containers running a bunch of actions of their startup, I lost the logs while debugging.

```
windmill_worker_native:
    # Use ghcr.io/windmill-labs/windmill-ee:main for the ee
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 128m # <- 
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RUST_LOG=debug
      - MODE=worker
      - WORKER_GROUP=native
    depends_on:
      db:
        condition: service_healthy
```

### To reproduce

1. Go to use a "native" script
2. Click on "test"
3. See result or logs
4. Re up the native worker containers with higher memory
5. See that native scripts work again

### Expected behavior

Native Worker should not be stuck an infinite loop.

Native workers should somehow throttle their memory usage? Setting the memory limit to something higher helps "clear it out" but could still happen.

### Application version

CE v1.186.0-8-g9df33ff6
