### ISSUE TITLE
 Unable to run scripts to access AWS resources, AccessDeniedException

### ISSUE THREAD

**Issue by murad-khafizov** [windmill-labs/windmill#2540]
I have self-hosted Windmill to run the scripts that query AWS-resources over "aws-sdk".

For that, I prepared a role in AWS and assigned all the necessary permissions to query the AWS resources.
Then I created a service account with the helm chart values:
```
serviceAccount:
  create: true
  name: SERVICE_ACCOUNT_NAME
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::ROLE_WITH_PERMISSIONS_TO_QUERY_AWS_RESOURCES
```
But when I try to run in Windmill my script, it says:
`AccessDeniedException: User: XXX is not authorized to perform: YYY because no identity-based policy allows the ZZZ action.`

What's important is that the user XXX is not the same as a SERVICE_ACCOUNT_NAME. 
So the worker pods in k8s still assume the wrong role. This makes me think, that some configuration is still missing or there is a bug.
