### ISSUE TITLE
bug: Early return causes no return (timeout) on exception 

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3701]
### Describe the bug

If an early return is used in a flow and an exception happens before the early return step, The error handler gets called, but the return result does not cause an actual return to the client.

Instead, it causes a timeout long after the flow has finished!

### To reproduce

1. Create new flow with two python script steps.
2. First step: Throw an error
3. Second step: Do nothing "def main: pass" 
4. Set second step as early return of flow
5. Enable error handler which returns e.g. status 400
6. Run flow through run_wait_result webhook => It never returns!

### Expected behavior

Error handler should still return and not cause a timeout!

### Browser information

Version 124.0.6367.119

### Application version

EE v1.323.6-12-gee2a19395

**Comment by wasnertobias** [comment]
Minimal flow to reproduce:
```
value:
  modules:
    - id: a
      value:
        lock: ""
        type: rawscript
        content: |-
          def main():
              raise AssertionError()
        language: python3
        input_transforms: {}
      summary: THROW ERROR
    - id: b
      value:
        lock: ""
        type: rawscript
        content: |-
          def main():
              pass
        language: python3
        input_transforms: {}
      summary: EMPTY EARLY RETURN
  early_return: b
  failure_module:
    id: failure
    value:
      type: rawscript
      content: |-
        def main(x: str):
            return {"windmill_status_code": 400}
      language: python3
      input_transforms:
        x:
          type: static
          value: null
summary: ""
description: ""
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties: {}
  required: []
```
