### ISSUE TITLE
bug: nodes may overlap in the flow editor in some rare edge cases

### ISSUE THREAD

**Issue by rubenfiszel** [windmill-labs/windmill#3842]
### Describe the bug

![image](https://github.com/windmill-labs/windmill/assets/275584/6bae0e64-a9ec-4177-9a79-ad3ad7b01587)

### To reproduce

```
summary: ""
value:
  modules:
    - id: a
      value:
        type: branchall
        branches:
          - modules:
              - id: b
                value:
                  type: branchall
                  branches:
                    - modules: []
                      skip_failure: false
                    - summary: ""
                      expr: "false"
                      modules: []
                      skip_failure: false
                    - summary: ""
                      expr: "false"
                      modules: []
                  parallel: false
                summary: ""
            skip_failure: false
          - summary: ""
            expr: "false"
            modules:
              - id: c
                value:
                  type: identity
                  flow: false
            skip_failure: false
          - summary: ""
            expr: "false"
            modules:
              - id: e
                value:
                  type: identity
                  flow: false
        parallel: false
      summary: ""
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  properties: {}
  required: []
  type: object

```

### Expected behavior

No overlap
