### ISSUE TITLE
bug: Error handlers allow "flow_input" as argument, but not "results"

### ISSUE THREAD

**Issue by wasnertobias** [windmill-labs/windmill#3884]
### Describe the bug

Highlighting is still broken for "flow_input".

Example flow attached.

### To reproduce

```
summary: ""
description: ""
value:
  modules:
    - id: b
      value:
        lock: ""
        type: rawscript
        content: |-
          # import wmill


          def main(x: str):
              return x + "someone"
        language: python3
        input_transforms:
          x:
            expr: flow_input.x
            type: javascript
        tag: ""
    - id: a
      value:
        tag: ""
        lock: ""
        type: rawscript
        content: |-
          # import wmill


          def main(x: str):
              raise Exception("ignore this please!")
        language: python3
        input_transforms:
          x:
            type: static
            value: ""
  failure_module:
    id: failure
    value:
      tag: null
      type: rawscript
      content: |
        # import wmill
        import logging

        logging.basicConfig(level=logging.INFO)

        def main(x: str, x2: str):
            logging.info("Got some" + x)
            logging.info(x2)
      language: python3
      input_transforms:
        x:
          expr: flow_input.x
          type: javascript
        x2:
          expr: results.b
          type: javascript
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  properties:
    x:
      type: string
      description: asdf
      default: ""
      format: ""
  required: []
  type: object
  order:
    - x

```

### Expected behavior

<img width="387" alt="image" src="https://github.com/windmill-labs/windmill/assets/1354793/d6173f46-2bdb-4d34-a606-fc7792d33a58">
Step input not underlined red if flow_input is used, as it apparently works. It would be nice to have access to step results that succeeded.
