### ISSUE TITLE
feature: windmill CLI Docker image

### ISSUE THREAD

**Issue by enote-kane** [windmill-labs/windmill#3943]
For integration into CI/CD systems, it would be nice to have a pre-built Docker image containing the `wmill` CLI tool, so that actions/jobs do not have to download the dependencies on each run.

The entrypoint **MAY** be pointing to the `wmill` executable, but arbitrary script execution via Bourne (again) shells **SHOULD** still be possible by replacing the entrypoint.

**Comment by rubenfiszel** [comment]
We will probably release such an image in the next few days

**Comment by rubenfiszel** [comment]
done: https://github.com/windmill-labs/windmill/pkgs/container/windmill-cli

**Comment by francescor** [comment]
thanks for the CLI Docker image, we really need it.


We are unfortunately unable to use it for the `wmill init` 

```
$  docker run --rm  ghcr.io/windmill-labs/windmill-cli --version
wmill 1.410.3
$ touch wmill.yaml
$ docker run --rm  -v ./wmill.yaml:/wmill.yaml ghcr.io/windmill-labs/windmill-cli init
wmill.yaml already exists
```

some basic bash commands would be usefult in the image (ls, cat, whoami, pause ...)

```
$ docker run --rm --entrypoint=/usr/bin/bash ghcr.io/windmill-labs/windmill-cli --version
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

Where can we find reference on what

**Comment by codersaur** [comment]
For anyone still struggling with the dockerised version of the CLI, here's my docker-compose. This creates a persistent container with the Windmill CLI, just need to connect to the container's console to run wmill commands.


```
  windmill-cli:
    container_name: windmill-cli
    image: ghcr.io/windmill-labs/windmill-cli:latest
    restart: unless-stopped
    user: 1000:1000                # Set user as needed, should match owner of workspace files.
    tty: true
    entrypoint: [ "/usr/bin/bash", "-l", "-c" ]
    command: ["tail", "-f", "/dev/null"]
    environment:
      # Make NodeJS trust extra certs:
      NODE_EXTRA_CA_CERTS: "/usr/local/share/ca-certificates/ca-certificates.crt" # Trust extra certs (mounted below).
    volumes:
      # Mount extra certs from docker host if we need NodeJS to trust additional CAs:
      - /etc/ssl/certs/ca-certificates.crt:/usr/local/share/ca-certificates/ca-certificates.crt:ro
      # Workspace Files:
      - /home/codersaur/windmill:/windmill:rw
```
