### ISSUE TITLE
feature: support typing.Optional for Python script parameters

### ISSUE THREAD

**Issue by enote-kane** [windmill-labs/windmill#3954]
Since Windmill already supports `typing.List` to recognize arrays, it totally makes sense to support `typing.Optional` for recognizing optional script parameters.

Example script:
```python
from typing import Optional

def main(required: str, opt: Optional[str]):
    print("OK")
```

Desired generated schema:
```yaml
summary: ''
description: ''
lock: '!inline f/transform/test.script.lock'
kind: script
schema:
  $schema: 'https://json-schema.org/draft/2020-12/schema'
  type: object
  properties:
    opt:
      type: string
      description: ''
      default: null
    required:
      type: string
      description: ''
      default: null
      originalType: string
  required:
    - required
```
