### ISSUE TITLE
bug: fill args from past runs in test flow not work for object field

### ISSUE THREAD

**Issue by ImSingee** [windmill-labs/windmill#4068]
### Describe the bug

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/15f94eac-0616-400e-be5f-3ed3defe56e0">

Click "Use Input" should fill the arg a, but not

### To reproduce

Demo flow:

```yaml
summary: ""
description: ""
value:
  modules:
    - id: a
      value:
        tag: ""
        lock: |-
          {
            "dependencies": {}
          }
          //bun.lockb
          <empty>
        type: rawscript
        content: |
          type Something = {}

          export async function main(a: Something) {
            return { foo: a };
          }
        language: bun
        input_transforms:
          a:
            expr: flow_input.a
            type: javascript
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  properties:
    a:
      description: ""
      type: object
      format: resource-something
      required: []
      nullable: false
  required:
    - a
  type: object
  order:
    - a
```

1. Run flow with a = `{"hello": "world"}`
2. Go to flow edit page, click "Test flow",
3. Click "Past Runs/Input library"
4. Choose the previous run, and click "Use Input"

### Expected behavior

arg `a` should be filled

### Browser information

Chromium Engine Version 126.0.6478.127

### Application version

Cloud (EE v1.361.1-3-gfd4fe15f4)
