### ISSUE TITLE
bug: Automatic replacement of step ID's doesn't work for iter expressions and predicates

### ISSUE THREAD

**Issue by MtlSnk** [windmill-labs/windmill#4368]
### Describe the bug

The title says it all: automatic replacement of step ID's doesn't work for iter expressions and predicates.

The bug was introduced with the new feature release of the YAML editor.

### To reproduce

1. Use this flow:
[bug-step-id-replacement-flow.json](https://github.com/user-attachments/files/16962943/bug-step-id-replacement-flow.json)

2. Edit the step id of `a` to `something`.
![image](https://github.com/user-attachments/assets/7be3315a-a848-4a10-8852-bc70a18e6162)

3. Check the iter expression on step `b` and the predicate on step `c`.

### Expected behavior

I'd expect that step ID's are replaced in iter expressions and predicates as well, seeing as the UI suggests they will be replaced under "Step Inputs Replacements".

### Application version

v1.394.0-3-gdecb4873f

**Comment by MtlSnk** [comment]
Wasn't entirely sure whether JSON flows could be imported again, so here's the YAML version of it as well

```yaml
summary: ""
value:
  modules:
    - id: a
      value:
        type: rawscript
        content: |
          export async function main() {
            return [1,2,3,4,5]
          }
        language: bun
        input_transforms: {}
        tag: ""
    - id: b
      value:
        type: forloopflow
        modules: []
        iterator:
          type: javascript
          expr: results.a
        skip_failures: true
        parallel: false
    - id: c
      value:
        type: branchone
        branches:
          - summary: results.a
            expr: results.a
            modules: []
        default: []
      summary: ""
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  properties: {}
  required: []
  type: object
```
