### ISSUE TITLE
bug:Retry delay value is ignored in steps within a while loop inside a flow with shared directory enabled.

### ISSUE THREAD

**Issue by tzatwork** [windmill-labs/windmill#4521]
### Describe the bug

If you enable shared directory as an option within a flow and you have a step that has a delay in retry (constant or exponential) the retry delay is ignored and the step will rapidly retry through the loop up to the total retry count.) 

### To reproduce

1. Create a flow with shared directory enabled.
2. Add a while loop to your flow
3. Add bash step as iteration with the contents of "exit 1".
4. Set retry to constant on that step, and set attempts to 100 and delay to 30 minutes.
5. Run your flow and watch all 100 attempts done quickly.
6. Disable shared directory and rerun your flow. Flow will properly respect 30 min delay. 

### Expected behavior

Steps with a configured delay should continue to respect the retry delay setting when shared directory is enabled within a flow.

### Application version

Tested on EE v1.407.2 or CE v1.405.4

### Additional Context

Described in discord thread https://discord.com/channels/930051556043276338/1293666282679566410

**Comment by mindplay-dk** [comment]
I was able to reproduce this issue.

```yaml
summary: ""
description: ""
value:
  modules:
    - id: a
      value:
        type: whileloopflow
        modules:
          - id: b
            value:
              type: script
              path: u/sumsarshoulez/insightful_flow/b
              hash: 169cb07f04a36e66
              input_transforms: {}
              is_trigger: false
            summary: ""
            retry:
              constant:
                attempts: 3
                seconds: 10
            continue_on_error: false
        skip_failures: false
        squash: false
  same_worker: true
  groups: []
schema:
  order: []
  properties: {}
```

This workflow completes in 1 second.

Turn off the `same_worker` and it runs in 3 iterations of 10 seconds, as expected.

I am just taking a first look at Windmill, and it's not yet clear to me how serious this issue is?

Would someone from the team care to comment? 😊
