### ISSUE TITLE
bug: WORKER_TAGS ignored for native worker

### ISSUE THREAD

**Issue by Bilge** [windmill-labs/windmill#4681]
### Describe the bug

Setting `WORKER_TAGS` appears to have no effect for the native worker

### To reproduce

```yaml
 windmill-worker-native:
    image: 'ghcr.io/windmill-labs/windmill:main'
    environment:
      - MODE=worker
      - WORKER_GROUP=native
      - NUM_WORKERS=3
      - SLEEP_QUEUE=200
      - WORKER_TAGS=deno,python3,go,bash,powershell,dependency,flow,other,bun,php,rust,ansible,nativets,postgresql,mysql,graphql,snowflake,mssql,bigquery
```

### Expected behavior

The specified worker tags are applied to the native worker.

### Screenshots

![image](https://github.com/user-attachments/assets/78caedaa-f967-4cdb-96c0-6ee556fb49ba)

### Browser information

Firefox 132.0.1 (64-bit)

### Application version

CE v1.421.2-6-gde9a839af

### Additional Context

Running `env` in a shell in the native worker container confirms the environment variable has been set as expected.

>env
```
WORKER_TAGS=deno,python3,go,bash,powershell,dependency,flow,other,bun,php,rust,ansible,nativets,postgresql,mysql,graphql,snowflake,mssql,bigquery
```
