### ISSUE TITLE
bug: Self-hosted worker report can not have INIT_SCRIPT customized through env var

### ISSUE THREAD

**Issue by whollacsek** [windmill-labs/windmill#5269]
### Describe the bug

On self-host `INIT_SCRIPT` doesn't work for worker group reports. It will always be:
```
apt-get update
apt-get install -y chromium
```

### To reproduce

Set `INIT_SCRIPT` on a self host instance and restart containers. Go to the runs and find the init_script tagged run. In the code tab it will be the predefined script instead of the content passed in env var.

### Expected behavior

`INIT_SCRIPT` should be taken into account by the worker

### Application version

Windmill 1.459

**Comment by jodiecunningham** [comment]
```
init_bash: config
            .init_bash
            .or_else(|| std::env::var("INIT_SCRIPT").ok())

```

It's because of the lines above. It has init_bash from the DB and the precedence takes the DB value. 
Just don't make a reports workers group, make another group with a different name.  I named mine "scrapers". 

From my values: 
```
        - name: scrapers
          replicas: 2
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1024Mi
          extraEnv:
            - name: "INIT_SCRIPT"
              value: "apt-get update\napt-get install -y chromium\npip install playwright\nexport PATH=$PATH:/tmp/.local/bin\nplaywright install\nplaywright install-deps"
            - name: "WORKER_TAGS"
              value: "chromium"
```
