### ISSUE TITLE
bug: Something going on with /tmp/windmill

### ISSUE THREAD

**Issue by eliah-w** [windmill-labs/windmill#5463]
### Describe the bug

All my bun scripts stopped working:

```
ExecutionErr: exit code for "bun build": 1, last log lines:
job=01957f92-e3f2-56cf-6b4c-23167788dba8 tag=bun worker=wk-default-f122e730754d-gEEEv hostname=f122e730754d


--- BUN INSTALL ---

error: Unexpected reading "/tmp/windmill/wk-default-f122e730754d-gEEEv/01957f92-e3f2-56cf-6b4c-23167788dba8/build.js"

Bun v1.2.3 (Linux x64 baseline)
```

As a workaround I converted some bun scripts to Deno, but connecting to a database is also not possible:
```
ConnectionError: Could not open socket in path "/tmp/.s.PGSQL.5432"
    at Connection.#openSocketConnection (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:288:17)
    at eventLoopTick (ext:core/01_core.js:177:7)
    at async Connection.#startup (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:337:7)
    at async Connection.startup (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:494:11)
    at async Client.connect (https://deno.land/x/postgres@v0.19.3/client.ts:233:7)
    at async main (file:///tmp/windmill/wk-default-dea918e60edc-i79Xz/01957f96-d21f-7852-0507-8db5b235cf1c/main.ts:23:5)
    at async run (file:///tmp/windmill/wk-default-dea918e60edc-i79Xz/01957f96-d21f-7852-0507-8db5b235cf1c/wrapper.ts:23:20)
    at async file:///tmp/windmill/wk-default-dea918e60edc-i79Xz/01957f96-d21f-7852-0507-8db5b235cf1c/wrapper.ts:29:5
```

I tried setting up a fresh windmill instance (same machine, different hard drive), but again even the hub_sync script fails to run with the same error.

My first assumption was permission errors, but bind-mounting /tmp/windmill didn't help either and I can't see any obvious permission errors. Here is an example from one of my workers:
```
root@dea918e60edc:/usr/src/app# ls -lah /tmp/windmill/
total 0
drwxrwxrwx 1 windmill windmill 192 Mar 10 10:13 .
drwxrwxrwt 1 root     root     366 Mar 10 09:16 ..
drwxrwxrwx 1     1024 users    184 Mar  9 23:53 cache
drwxrwxrwx 1 windmill windmill   0 Mar 10 09:16 cache_init
drwxrwxrwx 1 windmill windmill   6 Mar 10 09:16 cache_nomount
drwxrwxrwx 1     1024 users    376 Mar 10 10:25 logs
drwxr-xr-x 1 windmill windmill   0 Mar 10 09:17 search
drwxr-xr-x 1 root     root     504 Mar 10 10:25 wk-default-dea918e60edc-i79Xz
drwxr-xr-x 1 root     root       0 Mar 10 10:12 wk-default-dea918e60edc-j0rvQ
```

Let me know if you need more information, I am happy to help.
Kind regards.

### To reproduce

1. Setup windmill via docker-compose
2. Run hub_sync script

### Expected behavior

My scripts were running fine for months without any changes since then. This problem started occuring a few days ago, possibly after a windmill update.

**Comment by rubenfiszel** [comment]
We've hear some reports of this but we're unable to reproduce on fresh instances on docker-compose.
You would probably have the same issue with bun directly on your current setup: https://github.com/oven-sh/bun/issues/17629

If you can give us full reproduction step including the AMI image and host, and using vanilla docker-compose we may be able to investigate further. Note that we run windmill at scale on x64 and x86 and never faced those issues.

**Comment by eliah-w** [comment]
Running and bundling scripts with bun directly on my system works flawlessly.

You might not be able to reproduce this, I run it on my Synology NAS:
```
Model Name: DS1522+
CPU: AMD Ryzen R1600
OS version: DSM 7.2.2-72806 Update 3

Container Manager/Docker Daemon: 24.0.2-1535
```
Downgrading to Docker Daemon 20.10.23 shows no changes in behavior.

### How to reproduce
1. Basic Setup
```sh
curl https://raw.githubusercontent.com/windmill-labs/windmill/main/docker-compose.yml -o docker-compose.yml
curl https://raw.githubusercontent.com/windmill-labs/windmill/main/Caddyfile -o Caddyfile
curl https://raw.githubusercontent.com/windmill-labs/windmill/main/.env -o .env
```
2. Change volumes to local mappings, change server port, remove NanoCPUs (not supported on the system)
```yaml
version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "${LOG_MAX_SIZE:-20m}"
    max-file: "${LOG_MAX_FILE:-10}"
    compress: "true"

services:
  db:
    deploy:
      # To use an external database, set replicas to 0 and set DATABASE_URL to the external database url in the .env file
      replicas: 1
    image: postgres:16
    shm_size: 1g
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5438:5432
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: windmill
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging

  windmill_server:
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 1
    restart: unless-stopped
    expose:
      - 8000
      - 2525
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=server
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./worker_logs:/tmp/windmill/logs
    logging: *default-logging

  windmill_worker:
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 3
      resources:
        limits:
          #cpus: "1"
          memory: 2048M
          # for GB, use syntax '2Gi'
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=worker
      - WORKER_GROUP=default
    depends_on:
      db:
        condition: service_healthy
    # to mount the worker folder to debug, KEEP_JOB_DIR=true and mount /tmp/windmill
    volumes:
      # mount the docker socket to allow to run docker containers from within the workers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./worker_dependency_cache:/tmp/windmill/cache
      - ./worker_logs:/tmp/windmill/logs
    logging: *default-logging

  ## This worker is specialized for "native" jobs. Native jobs run in-process and thus are much more lightweight than other jobs
  windmill_worker_native:
    # Use ghcr.io/windmill-labs/windmill-ee:main for the ee
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 1
      resources:
        limits:
          #cpus: "1"
          memory: 2048M
          # for GB, use syntax '2Gi'
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=worker
      - WORKER_GROUP=native
      - NUM_WORKERS=8
      - SLEEP_QUEUE=200
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./worker_logs:/tmp/windmill/logs
    logging: *default-logging
  # This worker is specialized for reports or scraping jobs. It is assigned the "reports" worker group which has an init script that installs chromium and can be targeted by using the "chromium" worker tag.
  # windmill_worker_reports:
  #   image: ${WM_IMAGE}
  #   pull_policy: always
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: 2048M
  #         # for GB, use syntax '2Gi'
  #   restart: unless-stopped
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - MODE=worker
  #     - WORKER_GROUP=reports
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   # to mount the worker folder to debug, KEEP_JOB_DIR=true and mount /tmp/windmill
  #   volumes:
  #     # mount the docker socket to allow to run docker containers from within the workers
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - worker_dependency_cache:/tmp/windmill/cache
  #     - worker_logs:/tmp/windmill/logs

  # The indexer powers full-text job and log search, an EE feature.
  windmill_indexer:
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 0 # set to 1 to enable full-text job and log search
    restart: unless-stopped
    expose:
      - 8001
    environment:
      - PORT=8001
      - DATABASE_URL=${DATABASE_URL}
      - MODE=indexer
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./windmill_index:/tmp/windmill/search
      - ./worker_logs:/tmp/windmill/logs
    logging: *default-logging

  lsp:
    image: ghcr.io/windmill-labs/windmill-lsp:latest
    pull_policy: always
    restart: unless-stopped
    expose:
      - 3001
    volumes:
      - ./lsp_cache:/pyls/.cache
    logging: *default-logging
```
3. `docker-compose -d up`
4. Login as default admin, create user account, save settings
5. Navigate to superadmins workspace
6. Navigate to hub_sync script and run it. Response:
```
ExecutionErr: exit code for "bun install": 1, last log lines:
job=01958000-a0d7-c365-3a62-48df86e75361 tag=bun worker=wk-default-8d2d9a522ab5-pfzA9 hostname=8d2d9a522ab5

bun install v1.2.3 (8c4d3ff8)
error: Cannot read file "/tmp/windmill/wk-default-8d2d9a522ab5-pfzA9/01958000-a0d7-c365-3a62-48df86e75361/": Unexpected
error: Cannot read file "/tmp/windmill/wk-default-8d2d9a522ab5-pfzA9/01958000-a0d7-c365-3a62-48df86e75361/node_modules/esbuild/": Unexpected
```
