### ISSUE TITLE
bug: Input template from branch_one action output is always null

### ISSUE THREAD

**Issue by Bert-Proesmans** [windmill-labs/windmill#6076]
### Describe the bug

The flow editor allows using action results as input, also when those actions are part of a branch from "branch-one" that wouldn't be executed. I encounter a situation where the output of an earlier action within a branch-one step is always null for expression `return ("c" in results) ? results.c : null;`.

### To reproduce

1. Create a flow with a branch-one step and actions
2. Hook up the flow input with action inputs/outputs

<details>

<summary> Flow yaml </summary>

```yaml
summary: ""
description: ""
value:
  modules:
    - id: a
      value:
        lock: |
          # py312
        type: rawscript
        content: |-
          # import wmill


          def main(x: int):
              return x
        language: python3
        input_transforms:
          x:
            expr: flow_input.input
            type: javascript
    - id: b
      value:
        type: branchone
        default: []
        branches:
          - expr: results.a == 1
            modules:
              - id: c
                value:
                  lock: |
                    # py312
                  type: rawscript
                  content: |-
                    # import wmill


                    def main():
                        return "RESULT_ONE"
                  language: python3
                  input_transforms: {}
              - id: f
                value:
                  lock: |
                    # py312
                  type: rawscript
                  content: |
                    # import wmill


                    def main():
                        return "foobar"
                  language: python3
                  input_transforms: {}
            summary: "1"
            parallel: true
            skip_failure: true
          - expr: results.a == 2
            modules:
              - id: d
                value:
                  lock: |
                    # py312
                  type: rawscript
                  content: |
                    # import wmill


                    def main():
                        return "RESULT_TWO"
                  language: python3
                  input_transforms: {}
            summary: "2"
            parallel: true
            skip_failure: true
      summary: ""
    - id: e
      value:
        lock: |
          # py312
        type: rawscript
        content: |-
          # import wmill


          def main(x: str):
              return x
        language: python3
        input_transforms:
          x:
            expr: 'return ("c" in results) ? results.c : null;'
            type: javascript
      summary: result
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  properties:
    input:
      type: integer
  required: []
  type: object
  order:
    - input

```

</details>

3. Create a second flow, insert the previously created flow and hook up inputs/outputs

<details>

<summary> Flow yaml </summary>

```yaml

summary: ""
description: ""
value:
  modules:
    - id: a
      value:
        path: <REPLACE HERE WITH PATH TO PREVIOUS FLOW>
        type: flow
        input_transforms:
          input:
            type: javascript
            expr: flow_input.input
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  properties:
    input:
      type: integer
  required: []
  type: object
  order:
    - input


```

</details>

Run both flows and observe that the output for both of them with any input is always null, which is unexpected.

| Input | Output/Result |
| --- | --- |
| 0 | null |
| 1 | null |
| 2 | null |

### Expected behavior

Testing both flows, the first flow standalone and also the second flow, should end with the following result

| Input | Output/Result |
| --- | --- |
| 0 | null |
| 1 | RESULT_ONE |
| 2 | null |

### Browser information

Firefox version 139.0.4 (64-bit)

### Application version

Windmill enterprise version 1.501.4

### Additional Context

On older versions (<= 1.1474.0) *this used to work inconsistently* where I'd sometimes get non-null data from that expression but ONLY when running the first (inner) flow. The outer flow would result null consistently. (Triggered by applying incremental changes to the flow during experiments).
**EDIT**; The latest SAAS version has consistent behavior in inner and outer flow, **but the output/result is unexpected or under-documented**.
~~Since it's an inconsistency I cannot reproduce easily, also I have not been able to reproduce this at all on the latest SAAS version.~~
